name: Build multi-arch Docker Image

on:
  release:
    types: [published]
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.1
    - name: Login to Docker Hub
      # Only if we need to push an image
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Setup for buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.2.0
      with: 
        image: tonistiigi/binfmt:qemu-v6.0.0-12
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3.7.1
      with:
        version: v0.6.1

    # Debugging information
    - name: Docker info
      run: docker info
    - name: Buildx inspect
      run: docker buildx inspect

    # Build and (optionally) push the image
    - name: Build image
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        # Only push if we are publishing a release
        push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        # Use a 'temp' tag, that won't be pushed, for non-release builds
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name || 'temp' }}